# Generated by Django 5.1.1 on 2024-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipmaven_www", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapping",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
