# Generated by Django 5.1.1 on 2024-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmaven_www', '0002_mapping_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='score',
            field=models.IntegerField(default=50),
        ),
    ]
