# Generated by Django 5.1.1 on 2024-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmaven_www', '0003_alter_mapping_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='score',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
