# Generated by Django 5.1.1 on 2024-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipmaven_www", "0004_alter_mapping_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whois",
            name="code2",
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="whois",
            name="customer_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="whois",
            name="end_address",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="whois",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="whois",
            name="org_handle",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="whois",
            name="start_address",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
