# Generated by Django 5.1.1 on 2024-11-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmaven_www', '0005_alter_whois_code2_alter_whois_customer_name_and_more'),
        ('ipmaven_www', '0005_uploadedfile'),
    ]

    operations = [
    ]
