# Generated by Django 5.1.1 on 2024-12-03 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipmaven_www", "0006_merge_20241113_0857"),
        ("ipmaven_www", "0006_merge_20241203_0703"),
    ]

    operations = []
