# Generated by Django 4.2.9 on 2024-08-09 14:20

from django.db import migrations

def add_defaults(apps, schema_editor):

    agg = apps.get_model('bh_execute','Agg')

    agg.objects.create(
        max_variance = 12,
        min_records = 10,
        cluster_factor = 70,
        line_amounts = '1',
        min_delta_time = 1200000
    )

    conn_grp = apps.get_model('bh_execute','ByConnGroup')

    conn_grp.objects.create(
        conn_cnt = 10,
        conn_group = 10,
        threshold = 10
    )

    packet = apps.get_model('bh_execute','ByPacket')

    packet.objects.create(
        avg_delta = 10,
        conn_cnt = 10,
        min_unique_percent = 5
    )

    pconn = apps.get_model('bh_execute','ByPConn')

    pconn.objects.create(
        diff_time = 10,
        diff_type = 'mi',
    )

    dbscan = apps.get_model('bh_execute','DBScan')

    dbscan.objects.create(
        minimum_delta = 5,
        spans = '[0, 5], [2, 15], [15, 35], [30, 60]',
        minimum_points_in_cluster = 10,
        minimum_likelihood = 85,
    )

    dbscan_var = apps.get_model('bh_execute','DBScanVar')

    dbscan_var.objects.create(
        avg_delta = 20,
        conn_cnt = 20,
        span_avg = 12,
        variance_per = 15,
        minimum_likelihood = 85
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bh_execute', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_defaults)
    ]
