{
 "title": "Beacon",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count as \"Total Connections\"\nFROM raw_source"
    }
   ]
  },
  {
   "title": "Delta Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  connection_id as \"Delta Connections\"\nFROM delta\nWHERE\n  $__timeFilter(dt)"
    }
   ]
  },
  {
   "title": "Potential Beacons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(dest_ip,port)\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand dest_ip not in (select distinct ip from beacon_filter)"
    }
   ]
  },
  {
   "title": "Potential Beacons Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  dt AS \"time\",\n  count(port) as count\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand dest_ip not in (select distinct ip from beacon_filter)  \ngroup by dt\nORDER BY dt"
    }
   ]
  },
  {
   "title": "Potential Beacons",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\nsource_ip \"Source IP\",\ndest_ip as \"Destination IP\",\nport as \"Port\",\ncount(uid) as \"Connection Count\"\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand dest_ip not in (select distinct ip from beacon_filter)  \nGROUP BY source_ip, dest_ip, port"
    }
   ]
  }
 ]
}