{
 "title": "Beacon",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "uid",
    "label": "uid",
    "query": "select distinct uid from vw_beacon_group"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count as \"Total Connections\"\nFROM raw_source\nwhere group_id in (select group_id from beacon_group where uid = '$uid')"
    }
   ]
  },
  {
   "title": "Delta Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  connection_id as \"Delta Connections\"\nFROM delta\nWHERE\n  $__timeFilter(dt)\n  and group_id in (select group_id from beacon_group where uid = '$uid')\n  and dip not in (select distinct ip from beacon_filter)"
    }
   ]
  },
  {
   "title": "Potential Beacons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(source_ip,dest_ip,port)\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand dest_ip not in (select distinct ip from beacon_filter)\nand group_id in (select group_id from beacon_group where uid = '$uid')"
    }
   ]
  },
  {
   "title": "Potential Beacons Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  dt AS \"time\",\n  count(port) as count\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand group_id in (select group_id from beacon_group where uid = '$uid')\nand dest_ip not in (select distinct ip from beacon_filter)  \ngroup by dt\nORDER BY dt"
    }
   ]
  },
  {
   "title": "Potential Beacons",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT distinct \nsource_ip \"Source IP\",\ndest_ip as \"Destination IP\",\nport as \"Port\",\ncount(distinct uid) as \"Connection Count\"\nFROM beacon\nWHERE\n  $__timeFilter(dt)\nand dest_ip not in (select distinct ip from beacon_filter)  \nand group_id in (select group_id from beacon_group where uid = '$uid')\nGROUP BY source_ip, dest_ip, port"
    }
   ]
  }
 ]
}