# Generated by Django 4.2.2 on 2024-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conf_filter',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('filter', models.BooleanField(default=True)),
                ('port_filter', models.TextField(blank=True, default='')),
                ('port_exclude', models.BooleanField(default=False)),
                ('src_ip_filter', models.TextField(blank=True, default='')),
                ('src_ip_exclude', models.BooleanField(default=True)),
                ('dest_ip_filter', models.TextField(blank=True, default='')),
                ('dest_ip_exclude', models.BooleanField(default=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='conf_general',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_loc', models.CharField(max_length=256)),
                ('file_type', models.CharField(choices=[('1', 'Parquet'), ('2', 'CSV')], default=1, max_length=256)),
                ('overwrite', models.BooleanField(default=False)),
                ('verbose', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
