networks:
  bh_network:
    driver: bridge

services:
  db:
    container_name: bh_db
    image: mysql
    restart: always
    command: --init-file /setup/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'R00tB3aC0n!'
      MYSQL_DATABASE: 'beacon'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql
      - ./bh_web/beacon_huntress/src/setup/init.sql:/setup/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - bh_network          

  grafana:
    container_name: bh_grafana
    image: grafana/grafana
    user: root
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    ports:
      - '3000:3000'
    networks:
      - bh_network
    restart: always
    volumes:
      - ./bh_web/beacon_huntress/src/lib/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./bh_web/beacon_huntress/src/lib/grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./bh_web/beacon_huntress/src/lib/grafana/plugins:/var/lib/grafana/plugins/
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
    container_name: beacon_huntress
    command: >
      sh -c "python3 manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 bh_web.asgi:application"    
    restart: always
    volumes:
      - ./bh_web:/app
      - /tmp:/tmp
      - ./bh_web/datasets/tutorial:/tutorial
      - ./bh_web/datasets/elastic:/elastic
      - ./bh_web/datasets/zeek:/zeek
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
    networks:
      - bh_network      
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    container_name: bh_redis
    ports:
      - "6379:6379"
    networks:
      - bh_network      

  celery:
    build:
      context: .
    container_name: bh_celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0        
    volumes:
      - ./bh_web:/app
      - /tmp:/tmp
      - ./bh_web/datasets/tutorial:/tutorial
      - ./bh_web/datasets/elastic:/elastic
      - ./bh_web/datasets/zeek:/zeek  
    depends_on:
      - web
      - redis
    command: celery -A bh_web.celery worker --loglevel=debug    
    networks:
      - bh_network

volumes:
  db_data: 

